# HAMOYE DATA SCIENCE ASSESMENT SOLUTION SHEET
## The code illustrated below represent my calculation for the assesment in Introduction to Python for Machine Learning.

### Questions
##### Q1. If you're given two lists: A=[1,2,3,4,5,6], B=[13,21,34] The task is to create a list with element A and B in a single dimension with output: A_B=[1,2,3,4,5,6,13,21,34] What is the best way to create this list?
##### Q2. How do you create an Identity matrix in python?
##### Q3. Which of the fuel type code has the lowerest average fuel cost per unit burned?
##### Q4. What is the Standard Deviation and 75th percentile of the measureof energy per unit (Fuel_mmbtu_per_unit) in two decimal places?
##### Q5. What is the skewness and kurtosis for the fuel quantity burned in two decimal place?
##### Q6. What feature has the missing values and what is the total number of missing and percentage of missing rows as a factor of the total number of rows in three decimal places? (Enter answer in the format: Feature: xxx, Total: xxx, Percent: xxx)
##### Q7. The feature with missing value falls under what category? What missing value technique would you use?
##### Q8. Which feature has the second and third lowest correlation with the Fuel Cost Per Unit Burned?
##### Q9. For the Fuel type 'coal', what is the percentage changein the fuel cost per unit burned in 1998 compared to 1994?
##### Q10. Which year has the highest average fuel cost per unit delivered?

### Solutions

##### Python Library Importation

In [1]:
# Importing relevant libraries
import pandas as pd
import numpy as np

##### Data Preparation Phase

In [2]:
#url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
#data = pd.read_csv(url)
#data.to_csv('fuel_data.csv')
# UNHARSH THE ABOVE TO DOWNLOAD THE DATA
f_data = pd.read_csv('fuel_data.csv', index_col = 0)
f_data.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

#### Worksheet and Answers
###### Answer 1

In [3]:
'''The creation of a single dimension output with python function .extend()'''
A=[1,2,3,4,5,6]
B=[13,21,34] 
#The extend function help to add input for a continuous list
A_B = A.extend(B)
print(A)
print(B)
print('The extended output of A and B, Using extend():', A_B)

[1, 2, 3, 4, 5, 6, 13, 21, 34]
[13, 21, 34]
The extended output of A and B, Using extend(): None


###### Answer 2

In [4]:
'''The creation of an identity matrix: can be np.eye(), or np.identity()'''
print('As regard the option this is the correct answer.')
print(np.identity(3))
print('\nAnother way is:\n', np.eye(3))

As regard the option this is the correct answer.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Another way is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### Answer 3
###### Lowest Averages in Python

In [5]:
'''The lowerest average of fuel burn cost per unit of fuel type.'''
print(f_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean().nlargest(7))
print('\nAns 3: In the fuel per unit burned {} has the lowest average cost'.format(f_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean().nlargest(7)[-1]))

fuel_type_code_pudl
nuclear    4955.157002
oil         168.877086
coal         67.421830
waste        19.518122
other        18.253856
gas          13.659397
Name: fuel_cost_per_unit_burned, dtype: float64

Ans 3: In the fuel per unit burned 13.659396569737135 has the lowest average cost


##### Answer 4
###### Data Summary Statistics

In [6]:
'''An eye on the decription of the kind of data.'''
print('\nThe fuel_data shape is in {} rows and {} columns, as seen above.'.format(f_data.shape[0], f_data.shape[1]))
print('\nSome insight on the data, with summary statistics.\n')
print("Ans 4: For the Fuel energy in mmbtu, it's Standard deviation = ", round(f_data.fuel_mmbtu_per_unit.std(),2),
      "and the 75th Percentile = ", round(np.percentile(f_data.fuel_mmbtu_per_unit, 75),2))
f_data.describe(include='all')


The fuel_data shape is in 29523 rows and 11 columns, as seen above.

Some insight on the data, with summary statistics.

Ans 4: For the Fuel energy in mmbtu, it's Standard deviation =  10.6 and the 75th Percentile =  17.01


record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_1997_12_101_0_4               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

##### Answer 5
###### Level of Equalitiy Measurement

In [7]:
'''Consider the how asymetric or symetric the fuel quantity burned is to the data.'''
print('\nAns 5: For the fuel quantity burned, its skewness is {}, and the kurtosis is {}.'.format(round(f_data.fuel_qty_burned.skew(),2), round(f_data.fuel_qty_burned.kurt(),2)))


Ans 5: For the fuel quantity burned, its skewness is 15.85, and the kurtosis is 651.37.


##### Answer 6
###### Measure for Missing Values

In [8]:
'''Consider the percentage of missing data across columns and on the highest column of mimissing value.'''
print('Each columns in the fuel data has its null values represented below.\n', f_data.isnull().sum())
print('\nThe percentage of missing value across all fuel data features is:\n')
for col in f_data.columns:
    pct_missing = np.mean(f_data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100), 3))
print('\nAns 6: The missing data highest Feature is: {}, Total: {}, Percent: {}'.format(f_data.loc[:, f_data.isnull().any()].columns[0],
                                                   f_data.isnull().sum().nlargest(1)[0],
                                                   round(np.mean(f_data.isnull())*100, 3).nlargest(1)[0]))

Each columns in the fuel data has its null values represented below.
 record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

The percentage of missing value across all fuel data features is:

record_id - 0.0%
utility_id_ferc1 - 0.0%
report_year - 0.0%
plant_name_ferc1 - 0.0%
fuel_type_code_pudl - 0.0%
fuel_unit - 1.0%
fuel_qty_burned - 0.0%
fuel_mmbtu_per_unit - 0.0%
fuel_cost_per_unit_burned - 0.0%
fuel_cost_per_unit_delivered - 0.0%
fuel_cost_per_mmbtu - 0.0%

Ans 6: The missing data highest Feature is: fuel_unit, Total: 180, Percent: 0.61


##### Answer 7
###### Data Types, Data Category, Imputation Technique

In [9]:
'''Knowledge of the data type, data category and technique to solve missisng data in fuel unit column.'''
print('\nAlso each columns are presented in the following data types.\n', f_data.dtypes)
print('\nThe types of the data can be divided into two set; Numerical data types and Categorical data.')
print('\nThe Categorical data features in fuel dataset are: {}'.format(list(f_data.select_dtypes(include=['object']).copy().columns)))
print('\nWhile the Numerical data features in fuel dataset are: {}'.format(list(f_data.select_dtypes(include=['number']).copy().columns)))

# Diging in into the categorical feature of the missing value column [fuel unit].
print('\nWe identified that the missing value column is Fuel Unit. What method can we use to fill/replace the missing values?')
print('Using the fuel type code to further drill down on the fuel unit features.\n\nHere is the comparison between fuel unit by the type of fuel.\n',
      f_data.groupby(['fuel_type_code_pudl','fuel_unit'])['fuel_unit'].count())
print('\nAns 7: The missing data falls under Categorical features, the best technique to replace its missing values is with the Mode imputation')
print(f_data.info())


Also each columns are presented in the following data types.
 record_id                        object
utility_id_ferc1                  int64
report_year                       int64
plant_name_ferc1                 object
fuel_type_code_pudl              object
fuel_unit                        object
fuel_qty_burned                 float64
fuel_mmbtu_per_unit             float64
fuel_cost_per_unit_burned       float64
fuel_cost_per_unit_delivered    float64
fuel_cost_per_mmbtu             float64
dtype: object

The types of the data can be divided into two set; Numerical data types and Categorical data.

The Categorical data features in fuel dataset are: ['record_id', 'plant_name_ferc1', 'fuel_type_code_pudl', 'fuel_unit']

While the Numerical data features in fuel dataset are: ['utility_id_ferc1', 'report_year', 'fuel_qty_burned', 'fuel_mmbtu_per_unit', 'fuel_cost_per_unit_burned', 'fuel_cost_per_unit_delivered', 'fuel_cost_per_mmbtu']

We identified that the missing value column is 

##### Answer 8
###### Data Correlation

In [10]:
'''Measurement for the second and third lowest correlation for the fuel cost per unit burned.'''
cor = f_data.corr()
print('Ans 8: The second and third lowest correlation with fuel cost per unit burned column is:\n', abs(cor['fuel_cost_per_unit_burned']).sort_values()[1:3])

Ans 8: The second and third lowest correlation with fuel cost per unit burned column is:
 fuel_mmbtu_per_unit             0.010034
fuel_cost_per_unit_delivered    0.011007
Name: fuel_cost_per_unit_burned, dtype: float64


##### Answer 9
###### Percentage Changes

In [11]:
'''A percentage change in the cost of coal fuel delivered per unit between year 1998 and 1994'''
df = f_data.groupby([f_data['fuel_type_code_pudl'],f_data['report_year']])['fuel_cost_per_unit_burned'].sum()
# Calculation for percentage difference
diff = round(df.coal.iloc[4],2)-round(df.coal.iloc[0],2)
change = diff/round(df.coal.iloc[0],2)
perc = change*100
print('\nAns 9: The fuel burned cost change in the fuel type of coal between the year 1998 and 1994 is {}%'.format(round(perc)))


Ans 9: The fuel burned cost change in the fuel type of coal between the year 1998 and 1994 is -21.0%


##### Answer 10
###### Highest Averages

In [12]:
'''Calculation for the highest average of fuel cost per unit delivered by the report year'''
print('\nAns 10: The top average fuel cost per unit delivered in the report year category is:\n',
     round(f_data.groupby(['report_year'])['fuel_cost_per_unit_delivered'].mean().sort_values(ascending=False)).head())


Ans 10: The top average fuel cost per unit delivered in the report year category is:
 report_year
1997    11140.0
1996     9197.0
2000      985.0
2009      653.0
2018      499.0
Name: fuel_cost_per_unit_delivered, dtype: float64


## THANK YOU